name: Generate GitHub City

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/github-city.svg
          base: ""
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
